# Generated by Django 5.2.7 on 2025-11-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("legajo", models.IntegerField(unique=True)),
            ],
        ),
    ]
